# Generated by Django 3.1.4 on 2021-01-14 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('student_id', models.CharField(max_length=150)),
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_details', models.CharField(max_length=150)),
                ('classe_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Connect',
            fields=[
                ('connect_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_id', models.CharField(max_length=150)),
                ('teacher_id', models.CharField(max_length=150)),
                ('connect_status', models.CharField(max_length=150)),
                ('connect_seek_rating', models.CharField(max_length=150)),
                ('connect_teach_rating', models.CharField(max_length=150)),
                ('connect_rate', models.CharField(max_length=150)),
                ('student_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tutor.class')),
            ],
        ),
        migrations.CreateModel(
            name='Connect_Message_Attach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connect_message_id', models.CharField(max_length=60)),
                ('connect_attach_file_blob', models.CharField(max_length=60)),
                ('connect_attach_file_type', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email_id', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=250)),
                ('role', models.CharField(max_length=150)),
                ('seek_skills', models.CharField(max_length=150)),
                ('teach_skills', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=150)),
                ('rate', models.IntegerField()),
                ('rating', models.CharField(max_length=150)),
                ('level', models.CharField(max_length=150)),
                ('Languages', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Connect_Message',
            fields=[
                ('connect_message_id', models.AutoField(primary_key=True, serialize=False)),
                ('connect_message_ts', models.DateTimeField()),
                ('connect_message_text', models.TextField()),
                ('Is_Read', models.BooleanField()),
                ('connect_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tutor.connect')),
                ('connect_message_user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tutor.user')),
            ],
        ),
    ]
