# Generated by Django 3.1.4 on 2021-01-23 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_auto_20210123_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='connect_status',
            fields=[
                ('connect_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='country',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='level',
            fields=[
                ('level_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='rating',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=60, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='class',
            name='class_details',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='connect',
            name='connect_rate',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='connect',
            name='connect_seek_rating',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='connect',
            name='connect_status',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='connect',
            name='connect_teach_rating',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='connect_message_attach',
            name='connect_attach_file_blob',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='connect_message_attach',
            name='connect_attach_file_type',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='city',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=60, null=True)),
                ('country_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tutor.country')),
            ],
        ),
    ]
